import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import cache from '../helpers/cache'

const styles = {
  html: {
    minHeight: '100%',
    backgroundColor: '#705e91',
    color: "rgb(74, 74, 74)",
  }
}

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  cache.set('foo', 'bar')
  console.log({ foo: cache.get('foo') })

  return (
    <html lang="en" style={styles.html}>
      <head>
        <meta charSet="utf-8" />
        <title>Nuggets</title>
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </head>
      <body>{children}</body>
    </html>
  )
}
